### ISSUE TITLE
Adapter loop/restart

### ISSUE THREAD

**Issue by XDOM-JR** [iobroker-community-adapters/ioBroker.mihome-vacuum#702] opened 2022-11-25 16:43 UTC
**To Reproduce***
The adapter is looping. No map is loaded on every start

**Screenshots & Logfiles**  
2022-11-25 16:26:00.850 - debug: mihome-vacuum.0 (103274) Redis Objects: Use Redis connection: 127.0.0.1:9001
2022-11-25 16:26:00.862 - debug: mihome-vacuum.0 (103274) Objects client ready ... initialize now
2022-11-25 16:26:00.863 - debug: mihome-vacuum.0 (103274) Objects create System PubSub Client
2022-11-25 16:26:00.863 - debug: mihome-vacuum.0 (103274) Objects create User PubSub Client
2022-11-25 16:26:00.877 - debug: mihome-vacuum.0 (103274) Objects client initialize lua scripts
2022-11-25 16:26:00.879 - debug: mihome-vacuum.0 (103274) Objects connected to redis: 127.0.0.1:9001
2022-11-25 16:26:00.879 - silly: mihome-vacuum.0 (103274) redis psubscribe cfg.o.system.user.*
2022-11-25 16:26:00.884 - silly: mihome-vacuum.0 (103274) redis psubscribe cfg.o.enum.*
2022-11-25 16:26:00.886 - silly: mihome-vacuum.0 (103274) objectDB connected
2022-11-25 16:26:00.886 - debug: mihome-vacuum.0 (103274) Redis States: Use Redis connection: 127.0.0.1:9000
2022-11-25 16:26:00.890 - debug: mihome-vacuum.0 (103274) States create System PubSub Client
2022-11-25 16:26:00.890 - debug: mihome-vacuum.0 (103274) States create User PubSub Client
2022-11-25 16:26:00.938 - debug: mihome-vacuum.0 (103274) States connected to redis: 127.0.0.1:9000
2022-11-25 16:26:00.938 - silly: mihome-vacuum.0 (103274) statesDB connected
2022-11-25 16:26:00.966 - debug: mihome-vacuum.0 (103274) Plugin sentry Initialize Plugin (enabled=true)
2022-11-25 16:26:01.037 - info: mihome-vacuum.0 (103274) starting. Version 3.8.6 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v16.18.0, js-controller: 4.0.23
2022-11-25 16:26:01.052 - debug: mihome-vacuum.0 (103274) load Map creator... true
2022-11-25 16:26:01.094 - silly: mihome-vacuum.0 (103274) States system redis pmessage system.adapter.mihome-vacuum.0.logLevel/system.adapter.mihome-vacuum.0.logLevel:{"val":"silly","ack":true,"ts":1669393561052,"q":0,"from":"system.adapter.mihome-vacuum.0","lc":1669391183882}
2022-11-25 16:26:01.098 - debug: mihome-vacuum.0 (103274) Create State for deviceInfo
2022-11-25 16:26:01.098 - debug: mihome-vacuum.0 (103274) Create State for deviceInfomac
2022-11-25 16:26:01.098 - debug: mihome-vacuum.0 (103274) Create State for deviceInfomodel
2022-11-25 16:26:01.098 - debug: mihome-vacuum.0 (103274) Create State for deviceInfofw_ver
2022-11-25 16:26:01.098 - debug: mihome-vacuum.0 (103274) Create State for deviceInfowifi_signal
2022-11-25 16:26:01.098 - debug: mihome-vacuum.0 (103274) MIIO: Config: ip:192.168.1.119 token: 6545655031XXXXXXXXX
2022-11-25 16:26:01.099 - info: mihome-vacuum.0 (103274) IOT enabled, create state
2022-11-25 16:26:01.100 - debug: mihome-vacuum.0 (103274) server started on 0.0.0.0:53421
2022-11-25 16:26:01.112 - debug: mihome-vacuum.0 (103274) Receive <<< Helo <<< 21310020000000001ff00f0a0000caa5ffffffffffffffffffffffffffffffff
2022-11-25 16:26:01.112 - debug: mihome-vacuum.0 (103274) MAIN: Connected to device, try to get model..
2022-11-25 16:26:01.113 - debug: mihome-vacuum.0 (103274) Time difference between Mihome Vacuum and ioBroker: -1669341684 sec
2022-11-25 16:26:01.113 - debug: mihome-vacuum.0 (103274) GETMODELFROMAPI: objModel: {"val":"roborock.vacuum.a27","ack":true,"ts":1669393527539,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389778498}
2022-11-25 16:26:01.114 - debug: mihome-vacuum.0 (103274) Message= {"id":1,"method":"miIO.info"}
2022-11-25 16:26:01.123 - debug: mihome-vacuum.0 (103274) MIIO RECIVE: {"id":1,"result":{"life":51877,"model":"roborock.vacuum.a27","token":"654565503146707a6956737269697133","ipflag":1,"miio_ver":"0.0.9","uid":6609079726,"uptime":51889,"mac":"B0:4A:39:4E:50:0A","fw_ver":"4.3.5_5602","hw_ver":"Linux","miio_client_ver":"4.3.5","VmPeak":333488,"VmSize":268328,"VmRSS":2448,"MemFree":139996,"ap":{"ssid":"XDOM","bssid":"88:fc:a6:00:7b:81","rssi":"-63","freq":0},"netif":{"localIp":"192.168.1.119","mask":"255.255.255.0","gw":"192.168.1.1"},"miio_times":[51876,18,0,51856]},"exe_time":1}
2022-11-25 16:26:01.123 - debug: mihome-vacuum.0 (103274) GETMODELFROMAPI:Data: {"id":1,"result":{"life":51877,"model":"roborock.vacuum.a27","token":"6545655031XXXXXX":1}
2022-11-25 16:26:01.123 - debug: mihome-vacuum.0 (103274) Get Device data..0
2022-11-25 16:26:01.123 - debug: mihome-vacuum.0 (103274) Get Device data from robot.. {"life":51877,"model":"roborock.vacuum.a27","token":"6545655031XXXXXX":[51876,18,0,51856]}
2022-11-25 16:26:01.168 - debug: mihome-vacuum.0 (103274) DeviceModel selected to: roborock.vacuum.a27
2022-11-25 16:26:01.169 - info: mihome-vacuum.0 (103274) select standard vacuum protocol....
2022-11-25 16:26:01.170 - debug: mihome-vacuum.0 (103274) Xiaomi Cloud: Logging in
2022-11-25 16:26:01.181 - debug: mihome-vacuum.0 (103274) Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
2022-11-25 16:26:01.230 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.rooms.addRoom:{"val":"insert map Index or zone coordinates","ack":true,"ts":1669393561230,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389778599}
2022-11-25 16:26:01.679 - info: mihome-vacuum.0 (103274) settest next timer: not available
2022-11-25 16:26:01.681 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.nextTimer:{"val":"not available","ack":true,"ts":1669393561680,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389779079}
2022-11-25 16:26:01.919 - debug: mihome-vacuum.0 (103274) Login step1: &&&START&&&{"serviceParam":"{\"checkSafePhone\":false,\"checkSafeAddress\":false,\"lsrp_score\":0.0}","qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","code":70016,"description":"登录验证失败","securityStatus":0,"_sign":"0psXfr43eNI0IX6q9Suk3qWbRqU=","sid":"xiaomiio","result":"error","captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","location":"https://account.xiaomi.com/fe/service/login?_json=true&sid=xiaomiio&qs=%253Fsid%253Dxiaomiio%2526_json%253Dtrue&callback=https%3A%2F%2Fsts.api.io.mi.com%2Fsts&_sign=0psXfr43eNI0IX6q9Suk3qWbRqU%3D&serviceParam=%7B%22checkSafePhone%22%3Afalse%2C%22checkSafeAddress%22%3Afalse%2C%22lsrp_score%22%3A0.0%7D&showActiveX=false&theme=&needTheme=false&bizDeviceType=","pwd":0,"child":0,"desc":"登录验证失败"}
2022-11-25 16:26:02.532 - debug: mihome-vacuum.0 (103274) Login step2: &&&START&&&{"qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","ssecurity":"tnop5Lej6rytiRT1cIsO4Q==","code":0,"passToken":"V1:DXmurwq2/R1BHTELu6obCWvCum580FNwTVuGLgM9C7sCbhzrwfS9pN9aePLV7Tw2yDarxEWNYNavzH2h5mnMwzPkkoG6IAH3tAEJ+d/g65rQD8ltYN9ETxtVjveIlStIyifEbqlseTpDBw1N8v6kQd7ws/Pj+4VyoryPR5A8+8XiHc3Pseoy4aOITFaQ0yfmRkTT8j/s/EnPmTm7Z6cuB5//7kxfkI3he40UQxdv4zd92euhqnz1kihPeZMoU6pDe6rW8rl5hosowJ7ALJ8BXp60F7+Fwbq8OciM+OepWXc=","description":"成功","securityStatus":0,"nonce":3521739642560472064,"userId":6609079726,"cUserId":"N8P3WmUIpdC7HxHK47aOhEykoLA","result":"ok","psecurity":"Cw969ZMlR0i5HV8fyD8PUQ==","captchaUrl":null,"location":"https://sts.api.io.mi.com/sts?d=xogzzj&ticket=0&pwd=1&p_ts=1669393562000&fid=0&p_lm=1&auth=aUaKGVXUkETVh%2FP5zJmWNsFV5mB1q2a9Mlyn79IKFMFIy%2F54g7pVJmLAiQvMGTTklQvrQC%2FwGqrCf7dnqGxHeQyoWUJOD%2FPow8uYVLKrmKODg3wICo%2F46a9SQGUvZSFGPId2CAh2vqcpb3eTxE176mnyFt0zKWiPwT43wDjq5Cw%3D&m=1&_group=DEFAULT&tsl=0&p_ca=0&p_ur=CH&p_idc=Singapore&nonce=jwCOXt3JHUYBqIx6&_ssign=yfqJXR%2BYTk44TWWhVJ4QN3SmStw%3D","pwd":1,"child":0,"desc":"成功"}
2022-11-25 16:26:02.899 - debug: mihome-vacuum.0 (103274) Login step3: [{"key":"userId","value":"6609079726","domain":"sts.api.io.mi.com","path":"/","hostOnly":false,"creation":"2022-11-25T16:26:02.894Z","lastAccessed":"2022-11-25T16:26:02.899Z"},{"key":"cUserId","value":"N8P3WmUIpdC7HxHK47aOhEykoLA","domain":"sts.api.io.mi.com","path":"/","hostOnly":false,"creation":"2022-11-25T16:26:02.896Z","lastAccessed":"2022-11-25T16:26:02.899Z"},{"key":"serviceToken","value":"sqIDAaLvHXz+Idk7hmjr70obysRoB0lSy4cCnP/ioY9EDGu7ImfseKJWghvUdDhnPh/XA0f/11KUVsHgZKxjXEXRewiKYKXz/FzfyVE8PpdqBHFmRTZYlUKLb/Zj7VC/FYDAXi7ruTbut44BTHrvW9EfcOobQJYmLQvXHJ50VN0=","domain":"sts.api.io.mi.com","path":"/","hostOnly":false,"creation":"2022-11-25T16:26:02.897Z","lastAccessed":"2022-11-25T16:26:02.899Z"}]
2022-11-25 16:26:02.899 - debug: mihome-vacuum.0 (103274) Xiaomi Cloud: Login successful
2022-11-25 16:26:02.901 - debug: mihome-vacuum.0 (103274) Create State for control: {"id":"mihome-vacuum.0.control"}
2022-11-25 16:26:03.034 - debug: mihome-vacuum.0 (103274) Create State for Queue: queue
2022-11-25 16:26:03.078 - debug: mihome-vacuum.0 (103274) Create State for Queue: clearQueue
2022-11-25 16:26:03.122 - debug: mihome-vacuum.0 (103274) Create State for map:
2022-11-25 16:26:03.122 - debug: mihome-vacuum.0 (103274) Create State for map: map64
2022-11-25 16:26:03.122 - debug: mihome-vacuum.0 (103274) Create State for map: actualMap
2022-11-25 16:26:03.122 - debug: mihome-vacuum.0 (103274) Create State for map: mapStatus
2022-11-25 16:26:03.166 - debug: mihome-vacuum.0 (103274) Create State for map: mapURL
2022-11-25 16:26:03.166 - debug: mihome-vacuum.0 (103274) Create State for map: loadMap
2022-11-25 16:26:03.166 - debug: mihome-vacuum.0 (103274) Create State done!
2022-11-25 16:26:03.166 - debug: mihome-vacuum.0 (103274) get params for stock Vacuum
2022-11-25 16:26:03.166 - debug: mihome-vacuum.0 (103274) Message= {"id":2,"method":"get_status"}
2022-11-25 16:26:03.189 - debug: mihome-vacuum.0 (103274) MIIO RECIVE: {"id":2,"result":[{"msg_ver":2,"msg_seq":1474,"state":8,"battery":100,"clean_time":1,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"back_type":-1,"wash_phase":0,"wash_ready":0,"fan_power":104,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":202,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":389,"is_exploring":0,"home_sec_status":0,"home_sec_enable_password":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":3,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":0,"mop_mode":300,"debug_mode":0,"collision_avoid_status":0,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0}],"exe_time":10}
2022-11-25 16:26:03.189 - debug: mihome-vacuum.0 (103274) setGetStatus {"msg_ver":2,"msg_seq":1474,"state":8,"battery":100,"clean_time":1,"clean_area":0,"error_code":0,"map_present":true,"in_cleaning":false,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"back_type":-1,"wash_phase":0,"wash_ready":0,"fan_power":104,"dnd_enabled":false,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":202,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":389,"is_exploring":0,"home_sec_status":0,"home_sec_enable_password":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":3,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":0,"mop_mode":300,"debug_mode":0,"collision_avoid_status":0,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0,"error_text":"No error"}
2022-11-25 16:26:03.189 - info: mihome-vacuum.0 (103274) create states for mop
2022-11-25 16:26:03.190 - info: mihome-vacuum.0 (103274) change states from State control.fan_power
2022-11-25 16:26:03.190 - info: mihome-vacuum.0 (103274) create states for water box
2022-11-25 16:26:03.191 - debug: mihome-vacuum.0 (103274) Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
2022-11-25 16:26:03.191 - info: mihome-vacuum.0 (103274) create states for water box mode
2022-11-25 16:26:03.192 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.connection:{"val":true,"ack":true,"ts":1669393563191,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669393561125}
2022-11-25 16:26:03.196 - info: mihome-vacuum.0 (103274) create states for mop mode
2022-11-25 16:26:03.196 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.mop:{"val":true,"ack":true,"ts":1669393563192,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389778944}
2022-11-25 16:26:03.238 - info: mihome-vacuum.0 (103274) create states for dock status
2022-11-25 16:26:03.238 - info: mihome-vacuum.0 (103274) create states for dust collecting
2022-11-25 16:26:03.240 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.battery:{"val":100,"ack":true,"ts":1669393563239,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389778991}
2022-11-25 16:26:03.240 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.state:{"val":8,"ack":true,"ts":1669393563239,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389778991}
2022-11-25 16:26:03.240 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.cleanedtime:{"val":0,"ack":true,"ts":1669393563239,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389778991}
2022-11-25 16:26:03.240 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.cleanedarea:{"val":0,"ack":true,"ts":1669393563239,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389778991}
2022-11-25 16:26:03.241 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.control.fan_power:{"val":104,"ack":true,"ts":1669393563239,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389779034}
2022-11-25 16:26:03.282 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.error:{"val":0,"ack":true,"ts":1669393563282,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389779034}
2022-11-25 16:26:03.283 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.dnd:{"val":false,"ack":true,"ts":1669393563282,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389779034}
2022-11-25 16:26:03.283 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.cleanmap.actualMap:{"val":0,"ack":true,"ts":1669393563282,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389779034}
2022-11-25 16:26:03.326 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.cleanmap.mapStatus:{"val":3,"ack":true,"ts":1669393563326,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389779079}
2022-11-25 16:26:03.327 - debug: mihome-vacuum.0 (103274) Message= {"id":3,"method":"get_map_v1"}
2022-11-25 16:26:03.340 - debug: mihome-vacuum.0 (103274) MIIO RECIVE: {"id":3,"result":["retry"],"exe_time":10}
2022-11-25 16:26:03.382 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.connection:{"val":true,"ack":true,"ts":1669393563382,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669393561125}
2022-11-25 16:26:03.641 - debug: mihome-vacuum.0 (103274) Message= {"id":4,"method":"get_map_v1"}
2022-11-25 16:26:03.666 - debug: mihome-vacuum.0 (103274) MIIO RECIVE: {"id":4,"result":["roboroommap%2F535826186%2F8"],"exe_time":10}
2022-11-25 16:26:03.666 - debug: mihome-vacuum.0 (103274) Mappointer_updated
2022-11-25 16:26:03.666 - debug: mihome-vacuum.0 (103274) update_Map Mimap enabled
2022-11-25 16:26:03.666 - debug: mihome-vacuum.0 (103274) update_Map need new mapurl
2022-11-25 16:26:03.668 - debug: mihome-vacuum.0 (103274) Message= {"id":5,"method":"get_room_mapping"}
2022-11-25 16:26:03.684 - debug: mihome-vacuum.0 (103274) MIIO RECIVE: {"id":5,"result":[[16,"",1],[17,"",6],[18,"",9],[19,"",15],[20,"",14],[21,"",13],[22,"",8]],"exe_time":11}
2022-11-25 16:26:03.685 - debug: mihome-vacuum.0 (103274) Message= {"id":6,"method":"get_consumable"}
2022-11-25 16:26:03.685 - debug: mihome-vacuum.0 (103274) Message= {"id":7,"method":"get_network_info"}
2022-11-25 16:26:03.686 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.connection:{"val":true,"ack":true,"ts":1669393563686,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669393561125}
2022-11-25 16:26:03.691 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.connection:{"val":true,"ack":true,"ts":1669393563690,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669393561125}
2022-11-25 16:26:03.691 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.water_box:{"val":true,"ack":true,"ts":1669393563690,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780099}
2022-11-25 16:26:03.691 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.control.water_box_mode:{"val":202,"ack":true,"ts":1669393563690,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780099}
2022-11-25 16:26:03.691 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.dock_status:{"val":0,"ack":true,"ts":1669393563690,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780099}
2022-11-25 16:26:03.692 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.control.mop_mode:{"val":300,"ack":true,"ts":1669393563690,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780099}
2022-11-25 16:26:03.692 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.control.pauseResume:{"val":false,"ack":true,"ts":1669393563690,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780099}
2022-11-25 16:26:03.704 - debug: mihome-vacuum.0 (103274) MIIO RECIVE: {"id":6,"result":[{"main_brush_work_time":244054,"side_brush_work_time":244054,"filter_work_time":244054,"filter_element_work_time":0,"sensor_dirty_time":2,"strainer_work_times":44,"dust_collection_work_times":86,"cleaning_brush_work_times":197}],"exe_time":10}
2022-11-25 16:26:03.704 - debug: mihome-vacuum.0 (103274) Message= {"id":8,"method":"get_clean_summary"}
2022-11-25 16:26:03.706 - info: mihome-vacuum.0 (103274) create new room:
2022-11-25 16:26:03.751 - error: mihome-vacuum.0 (103274) uncaught exception: Cannot create a channel without a name!
2022-11-25 16:26:03.751 - error: mihome-vacuum.0 (103274) Error: Cannot create a channel without a name!
2022-11-25 16:26:03.751 - error: mihome-vacuum.0 (103274) Cannot create a channel without a name!
2022-11-25 16:26:03.756 - error: mihome-vacuum.0 (103274) Socket Close
2022-11-25 16:26:03.756 - info: mihome-vacuum.0 (103274) terminating
2022-11-25 16:26:03.756 - debug: mihome-vacuum.0 (103274) Plugin sentry destroyed
2022-11-25 16:26:03.756 - warn: mihome-vacuum.0 (103274) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-11-25 16:26:03.757 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.info.connection:{"val":true,"ack":true,"ts":1669393563705,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669393561125}
2022-11-25 16:26:03.757 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.consumable.main_brush:{"val":77,"ack":true,"ts":1669393563705,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780167}
2022-11-25 16:26:03.758 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.consumable.side_brush:{"val":66,"ack":true,"ts":1669393563757,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780167}
2022-11-25 16:26:03.762 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.consumable.filter:{"val":55,"ack":true,"ts":1669393563757,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780168}
2022-11-25 16:26:03.762 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.consumable.sensors:{"val":100,"ack":true,"ts":1669393563757,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1669389780168}
2022-11-25 16:26:03.830 - debug: mihome-vacuum.0 (103274) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/roboroommap/535826186/8?Expires=1669395363000&GalaxyAccessKeyId=5271733786445&Signature=z5wPXkPr4zBk+JNI1mzFRv+3LJc=
2022-11-25 16:26:03.830 - debug: mihome-vacuum.0 (103274) update_Map got new expires:1669395363
2022-11-25 16:26:03.830 - debug: mihome-vacuum.0 (103274) update_Map got new time:1669393563
2022-11-25 16:26:04.033 - silly: mihome-vacuum.0 (103274) States user redis pmessage mihome-vacuum.0.*/mihome-vacuum.0.cleanmap.map64:{"val":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoQAAATUCAYAAADx6RaCAAAABmJLR0QA/wD/AP+gvaeTAAAgAElEQVR4nOzdeZTd9Xnf8c+9c2e0jaTRAkgIBMhsAsy+BIJtMfKCHWNwszlOnMRN6iTYaXyOazempWlLK9tJ3MZxmp5D0qZtYidp3TTgAHZAYzCKBbYxm4OQjS2EjBaE9n2Zuf1DNkZCRggtd0bP63UO53B1ZzRf3UHifR499/dLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAw6nR6QMAHC1z+/vbnT7DsWz+wID/p8AI1ez0AQAA6CxBCABQnCAEACjOvgdwxAz3nb2brhzo9BFGtHkL+zv69e0swuFjQggAUJwgBAAoThACABRn/wI4YvbdIez0zt6+O2+dPg8Hp9M7iwfLjiMjiQkhAEBxghAAoDhBCABQXKvTBwCAV2Lfnc/hthM60nYc4cVMCAEAihOEAADFCUIAgOIEIQBAcYIQAKA4QQgAUJwgBAAoThACABQnCAEAihOEAADFCUIAgOIEIQBAcYIQAKA4QQgAUJwgBAAortXpAwB1zFvY3+kjALAfJoQAAMUJQgCA4gQhAEBxdgiBo+amKwc6fQQA9sOEEACgOEEIAFCcIAQAKE4QAgAUJwgBAIoThAAAxQlCAIDiXIcQgBHJdS3h8DEhBAAoThACABQnCAEAihOEAADFCUIAgOIEIQBAcYIQAKA4QQgAUJwgBAAoThACABQnCAEAihOEAADFCUIAgOIEIQBAcYIQAKA4QQgAUJwgBAAoThACABQnCAEAihOEAADFCUIAgOIEIQBAcYIQAKA4QQgAUJwgBAAoThACABQnCAEAimt1+gBH29z+/nanzwAAMJyYEAIAFCcIAQCKE4QAAMWV2yHc101XDnT6CCPKvIX9ez32+gHAyGdCCABQnCAEAChOEAIAFCcIAQCKE4QAAMUJQgCA4gQhAEBxghAAoDhBCABQnCAEAChOEAIAFFf+XsYcnEO9d7F7IQPA8GNCCABQnCAEAChOEAIAFCcIAQCKE4QAAMUJQgCA4gQhAEBxghAAoDhBCABQnCAEAChOEAIAFCcIAQCKE4QAAMUJQgCA4gQhAEBxghAAoDhBCABQnCAEAChOEAIAFCcIAQCKE4QAAMUJQgCA4gQhAEBxghAAoDhBCABQnCAEAChOEAIAFCcIAQCKE4QAAMUJQgCA4gQhAEBxghAAoDhBCABQnCAEAChOEAIAFCcIAQCKE4QAAMUJQgCA4gQhAEBxghAAoDhBCABQnCAEAChOEAIAFCcIAQCKE4QAAMUJQgCA4gQhAEBxghAAoDhBCABQnCAEAChOEAIAFNfq9AEA4JWYt7C/00eAY5YJIQBAcYIQAKA4QQgAUJwdQgBGhJuuHOj0EV6WHUdGMhNCAIDiBCEAQHGCEACgOEEIAFCcIAQAKE4QAgAUJwgBAIoThAAAxQlCAIDiBCEAQHGCEACgOEEIAFCcIAQAKE4QAgAUJwgBAIoThAAAxQlCAIDiBCEAQHGCEACgOEEIAFCcIAQAKE4QAgAUJwgBAIoThAAAxQlCAIDiBCEAQHGCEACgOEEIAFCcIAQAKE4QAgAUJwgBAIoThAAAxQlCAIDiBCEAQHGCEACgOEEIAFCcIAQAKE4QAgAUJwgBAIprdfoAAPBqzFvY3+kjwDHDhB ...

**Versions:**

-   Adapter version: 3.8.6
-   JS-Controller version: 4.0.23
-   Node version: v16.18.0
-   vacuum cleaner: Roborock S7 MaxV

**Comment by dirkhe** [comment] 2022-11-25 17:31
The problem is the following:
{"id":5,"method":"get_room_mapping"}
2022-11-25 16:26:03.684 - debug: mihome-vacuum.0 (103274) MIIO RECIVE: {"id":5,"result":[[16,"",1],[17,"",6],[18,"",9],[19,"",15],[20,"",14],[21,"",13],[22,"",8]],"exe_time":11}

expected is here something like
[[16,"111111"],[17,"222222"]....],

the 1111111  and 222222 are the ID's from the cloud, which are empty. But you get a 3rd Number for every Room. What does this number say??? We need a uniqie id here. So something seem's to be changed for your model or generell in firmware. Did you updated your firmware? Does it works until update?

**Comment by XDOM-JR** [comment] 2022-11-25 17:38
I have the newst Firmware:

Modell : roborock.vacuum.a27, Seriennummer : R21ETS21700860, Firmwareversion : 4.3.5_5602, Plug-in-Version : MI_MDX_2752, MI-ID : 6609079726, Roboter-Zeitzone : Europe/Zurich, WLAN-Name : XDOM, IP-Adresse : 192.168.1.119, MAC-Adresse : B0:4A:39:4E:50:0A,

**Comment by dirkhe** [comment] 2022-11-25 17:44
The question is, did it work in the beginning or do install apadpter first time? I want to know, if there changes  in the firmware or if this only for your model? 
And what does the 3rd. parameter means?
Can you try to give your rooms names? Can you try to delete a room or split a room?  Waht does the will be returnes than by get_room_mapping.
If we then have an Idea, I can try to implment a hotfix

**Comment by XDOM-JR** [comment] 2022-11-25 17:49
its working after renaming the Kitchen(Küche) to Kitchen

**Comment by dirkhe** [comment] 2022-11-25 18:28
Ok, can you post your room mapping niw, you can add get_room_mapping to custom command

**Comment by dirkhe** [comment] 2022-11-26 10:02
fixed in 3.8.7

**Closed by dirkhe** 2022-11-26 10:02 UTC
Labels: Must be fixed
