### ISSUE TITLE
map error:SyntaxError: Unexpected token h in JSON at position 0

### ISSUE THREAD

**Issue by Michaelnorge** [iobroker-community-adapters/ioBroker.mihome-vacuum#489] opened 2022-01-22 16:31 UTC
After update to v. 3.3.4 (also 3.3.3) I got this error:

`<html><body>

2022-01-22 17:18:05.928  - info:  mihome-vacuum.0 (18908) starting. Version 3.3.3 in  /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.18.3,  js-controller: 3.3.22
--
2022-01-22 17:18:06.044  - info: mihome-vacuum.0 (18908) IOT enabled, create state
2022-01-22 17:18:16.082  - warn:  mihome-vacuum.0 (18908) YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET  - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT  TURN THE ADAPTER OFF
2022-01-22 17:18:16.083  - warn: mihome-vacuum.0 (18908) No Answer for DeviceModel use old one
2022-01-22 17:18:16.084  - warn: mihome-vacuum.0 (18908) No Answer for DeviceModel use model from Config
2022-01-22 17:18:16.155  - info: mihome-vacuum.0 (18908) select standard vacuum protocol....
2022-01-22 17:18:16.682  - info: mihome-vacuum.0 (18908) settest next timer: not available
2022-01-22 17:18:17.921  - info: mihome-vacuum.0 (18908) Map selected create states...
2022-01-22 17:20:00.089  - info: host.raspberrypi instance system.adapter.netatmo-crawler.0 started with pid 19371
2022-01-22 17:20:10.269  - info: host.raspberrypi instance system.adapter.netatmo-crawler.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-01-22 17:25:00.115  - info: host.raspberrypi instance system.adapter.netatmo-crawler.0 started with pid 20617
2022-01-22 17:25:09.701  - info: host.raspberrypi instance system.adapter.netatmo-crawler.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-01-22 17:25:50.034  - info: mihome-vacuum.0 (18908) create state for carpet_mode
2022-01-22 17:26:10.111  - info: mihome-vacuum.0 (18908) change states from State control.fan_power
2022-01-22 17:26:10.122  - info: mihome-vacuum.0 (18908) create states for water box
2022-01-22 17:26:12.047  - error: mihome-vacuum.0 (18908) Error when receiving map url: h-s>D;y/5>EnJR]':vU\B~;QVD=Xa;l(%mLG.izj5xx  E+V\Da&7Ydy+%V%yLT'{]IH`Kk(  V0VB\|_M7(C+{Z.X&S}[\|!aJd>L!C$}z&
D>0#:Z%5_wyi(}*.8Y$XWD[Nwq4,bn2^p"Qw?@Bv ypj
InrM5f 'th*kRksn('9,SrQ*wX1b*bVc47`pWIlQ%qnxlJ!T$!*
2022-01-22 17:26:12.049  - warn: mihome-vacuum.0 (18908) map error:SyntaxError: Unexpected token h in JSON at position 0
2022-01-22 17:26:12.858  - info:  mihome-vacuum.0 (18908) Room array empty... generate from mapdata..  [[1,"room1"],[17,"room17"],[19,"room19"],[18,"room18"],[16,"room16"],[5,"room5"]]

</body>
</html>`

I am using a Roborock S5

**Comment by Diginix** [comment] 2022-01-22 19:19
seems to be a duplicate of https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/488

**Comment by dirkhe** [comment] 2022-01-22 20:13
Please send debug log and use 3.3.4. The problem seems a timing issue

**Closed** 2022-01-23 08:30 UTC
